version: '3'

services:
  mongodb:
    image: mongo:4.0.13
    container_name: mongo-4
    networks:
    - mongo
    volumes:
    - './data:/data'
    environment:
    - MONGO_INITDB_ROOT_USERNAME=sigl2020
    - MONGO_INITDB_ROOT_PASSWORD=sigl2020
  mongo-express:
    image: mongo-express:0.49.0
    container_name: mongo-express
    networks:
    - mongo
    environment:
    - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
    - ME_CONFIG_MONGODB_SERVER=mongo-4
    - ME_CONFIG_MONGODB_AUTH_USERNAME=sigl2020
    - ME_CONFIG_MONGODB_AUTH_PASSWORD=sigl2020
    ports:
    - 8081:8081

networks:
  mongo:
    external:
      name: mongo
