name: Build docs

on:
  push:
    branches: 
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: kamiazya/setup-graphviz@v1
    - name: Generate entity relation diagram
      run: |
       dot -Tpng docs/erd.dot -o docs/erd.png